import {
  BlueprintIcon,
  BookIcon,
  BriefcaseIcon,
  BuildingIcon,
  BundleIcon,
  ChartLineIcon,
  CloudServerIcon,
  ClusterIcon,
  CodeIcon,
  CoinsIcon,
  CogIcon,
  CommentsIcon,
  CompassIcon,
  DatabaseIcon,
  DesktopIcon,
  FileIcon,
  FlaskIcon,
  FolderOpenIcon,
  HandshakeIcon,
  HandsHelpingIcon,
  HeartIcon,
  HomeIcon,
  IdBadgeIcon,
  KeyIcon,
  LandmarkIcon,
  MemoryIcon,
  MicrochipIcon,
  NetworkIcon,
  OutlinedHeartIcon,
  OutlinedStarIcon,
  ProcessAutomationIcon,
  ProjectDiagramIcon,
  SecurityIcon,
  ServerIcon,
  ShoppingCartIcon,
  StorageDomainIcon,
  TachometerAltIcon,
  ToolboxIcon,
  TrendUpIcon,
  TrophyIcon,
  TruckIcon,
  UndoIcon,
  UsersIcon,
  BoltIcon,
  MapMarkedAltIcon,
} from "@patternfly/react-icons";
import type { ReactElement } from "react";

const ICONS: Record<string, ReactElement> = {
  dashboard: <TachometerAltIcon />,
  science: <FlaskIcon />,
  account_tree: <ProjectDiagramIcon />,
  schema: <BlueprintIcon />,
  description: <FileIcon />,
  folder_special: <FolderOpenIcon />,
  account_balance: <LandmarkIcon />,
  savings: <CoinsIcon />,
  payments: <CoinsIcon />,
  volunteer_activism: <HandsHelpingIcon />,
  work: <BriefcaseIcon />,
  handyman: <ToolboxIcon />,
  emoji_events: <TrophyIcon />,
  badge: <IdBadgeIcon />,
  server: <ServerIcon />,
  storage: <StorageDomainIcon />,
  cluster: <ClusterIcon />,
  cube: <BundleIcon />,
  bolt: <BoltIcon />,
  database: <DatabaseIcon />,
  memory: <MemoryIcon />,
  stream: <ProcessAutomationIcon />,
  users: <UsersIcon />,
  shield: <SecurityIcon />,
  cogs: <CogIcon />,
  cart: <ShoppingCartIcon />,
  trend: <TrendUpIcon />,
  key: <KeyIcon />,
  handshake: <HandshakeIcon />,
  truck: <TruckIcon />,
  landmark: <LandmarkIcon />,
  comments: <CommentsIcon />,
  coins: <CoinsIcon />,
  book: <BookIcon />,
  stamp: <FileIcon />,
  chart: <ChartLineIcon />,
  file: <FileIcon />,
  list: <FolderOpenIcon />,
  code: <CodeIcon />,
  flask: <FlaskIcon />,
  broadcast: <CloudServerIcon />,
  heartbeat: <HeartIcon />,
  compass: <CompassIcon />,
  project: <ProjectDiagramIcon />,
  blueprint: <BlueprintIcon />,
  folder: <FolderOpenIcon />,
  star: <OutlinedStarIcon />,
  leaf: <HomeIcon />,
  heart: <OutlinedHeartIcon />,
  map: <MapMarkedAltIcon />,
  desktop: <DesktopIcon />,
  microchip: <MicrochipIcon />,
  network: <NetworkIcon />,
  undo: <UndoIcon />,
  building: <BuildingIcon />,
};

export function NavIcon({ name }: { name: string }) {
  return ICONS[name] ?? <TachometerAltIcon />;
}
